services:
  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rentalmanagement:
    build:
      context: ./RentalManagement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RentalManagementContext=Host=postgres;Port=5432;Database=rental_management;Username=postgres;Password=postgrespw

  frontend:
    build:
      context: ./rental-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rentalmanagement
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./rental-management-frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
